#ifndef DEFINES_HPP_INCLUDED
#define DEFINES_HPP_INCLUDED

#define IP_ADDRESS  127.0.0.1
#define PORT_NUMBER 8749
#define DEFAULT_PORT_NUMBER 8749
#define BACK_LOG    20
#define MAX_BUF_LEN 1024



#endif // DEFINES_HPP_INCLUDED
